#
# Generated By "genmake"
# Date : 2017.06.30
# YJYOON
#
# OBJ1 : Basic library (thread safe)
# OBJ2 : Application library (thread unsafe)
#


LD_HOME         = $(HOME)/Project
CC              = gcc
AR              = ar
SYSTEM_INCL     = 
COMMON_INCL     = -I$(LD_HOME)/include
LOCAL_INCL      =
INCLUDE         = $(LOCAL_INCL) $(COMMON_INCL) $(SYSTEM_INCL)
SUBDIRS= sample


LIBNAME1        =$(LD_HOME)/lib/libTbC.a
LIBNAME2        =$(LD_HOME)/lib/libTbzmq.a


CFLAGS          = -D_REENTRANT -g -c $(INCLUDE)
ARFLAGS         = rcs

.SUFFIXES       : .cc .c .o .cp

.c.o            :
	$(CC) $(CFLAGS) $*.c

.cc.o            :
	$(CC) -std=c++11 $(CFLAGS) $*.cc

# OBJS list
OBJS1 = binsearch.o calday.o ctlmsg.o doublefun.o envfile.o event.o \
getYmd.o getcurrtimelong.o getfilesz.o getmyaddr.o getport.o \
getport_r.o getwinsize.o makemap.o memcpy.o strcmp.o mpfr.o  \
npack.o openmtpub.o openmtsub.o readfd.o readst.o isrun.o \
setwinsize.o  strdbl.o streamcli.o streamclis.o streamsvr.o \
strtrim.o syncmmap.o tbjson.o timerfd.o unmmap.o unstrcli.o  unstrsvr.o \
waitconnect.o writefd.o writest.o writev.o clsfile.o linkedlst.o \
st_logout.o  mt_logout.o event_v2.o yyjson.o libnetlog.o

OBJS2 = zmqctlmsg.o zmqevent.o zmqevent_arg.o zmqisrun.o zmqlogout.o \
zmqlogout_thr.o zmqmsgrcv.o zmqmsgsnd.o zmqopenpub.o zmqopenpull.o \
zmqopenrep.o zmqopenreq.o zmqopensub.o zmqsetsub.o zmqtopicmsgrcv.o \
zmqtopicmsgsnd.o zmqtopicrcv.o zmqtopicsnd.o zmqgetproxyenv.o \
zmqgetfd.o zmqsockmon.o

all : lib1 lib2

lib1            : $(OBJS1)
	$(AR) $(ARFLAGS) $(LIBNAME1) $(OBJS1)
	@make clean
lib2            : $(OBJS2)
	$(AR) $(ARFLAGS) $(LIBNAME2) $(OBJS2)
	@make clean

clean           :
#	@for i in $(SUBDIRS); do (cd ./$$i && echo $$i: && $(MAKE) $@) done || exit 1

	 rm -f *.o core
